### ISSUE TITLE
lsp update logic breaks functionality

### ISSUE THREAD

**Issue by laur89** [NoahTheDuke/coc-clojure#11]
coc-clojure had already been installed, and everything worked fine for a few days.
Now when opening a .clj file, the `clojure-lsp is outdated. Download from Github?` message started showing again. Selecting either choice closes the pop-up message but does nothing (ie clojure-lsp isn't updated nor are any errors shown) and no syntax errors are highlighted, suggesting the communication with lsp is broken.

If `"clojure.lsp-check-on-start": false` is set in `~/.config/nvim/coc-settings.json` however, then the currently installed lsp works and syntax errors are shown.

How to proceed?

-----
```
vim version: NVIM v0.7.2
node version: v19.5.0
coc.nvim version: 0.0.82-b7375d5f 2023-01-30 05:09:03 +0800
coc-clojure Current version 0.0.14

$ cat ~/.config/coc/extensions/coc-clojure-data/clojure-lsp-version
2023.05.04-19.38.01
```

**Comment by NoahTheDuke** [comment]
Uh oh! Thanks for letting me know. I'll take a look and see if I can get it fixed for you.

**Comment by laur89** [comment]
Note it only breaks if LSP has already been downloaded. If you remove `~/.config/coc/extensions/coc-clojure-data/` (that's the default location), then the startup logic nicely pulls fresh version and everything works a-ok.
