### ISSUE TITLE
some commands like `lsp-clojure-extract-function` don't work

### ISSUE THREAD

**Issue by nimaai** [NoahTheDuke/coc-clojure#14]
Some refactoring commands like `lsp-clojure-extract-function` don't work:

`[coc.nvim] Error: Internal error`

I assume because they expect an input from the user?

**Comment by nimaai** [comment]
It works through `<Plug>(coc-codeaction-refactor)` interactive popup window.

**Comment by NoahTheDuke** [comment]
I just released 0.0.17 which fixes this. Thanks for catching it!
