### ISSUE TITLE
Loading clojure-lsp doesn't go away on a non-clojure file

### ISSUE THREAD

**Issue by dharrigan** [NoahTheDuke/coc-clojure#7]
Hi,

If I have a non-clojure file, say a sql file, in a clojure project and open it up in neovim, the  message `Loading clojure-lsp` along with the little spinner is displayed, but doesn't go away. I don't recall this happening before.

-=david=-

**Comment by NoahTheDuke** [comment]
That does sound annoying. I wonder why it's taking so long to load/crashing and not loading at all. Is the code base available for me to poke around in? Maybe I can recreate your issue.

**Comment by NoahTheDuke** [comment]
Let me think on this today, cuz my workflow is "single vim window for all work in a given repository", and being able to seamlessly go from readme to clojure without any pause (while I wait for clojure-lsp to load) is really nice.

**Comment by dharrigan** [comment]
Hi, just did a quick test. If I edit your package.json, removing the activation events (keeping the `onLangauge:clojure`) and build, then if I open up a sql file the `clojure-lsp` is not loaded (as expected). As soon as I edit a clj file, clojure-lsp is loaded (as expected). 

```
❯ ps aux | rg clojure-lsp
david     574529  4.8  0.8 645288 537832 ?       Sl   15:17   0:06 /bin/clojure-lsp
david     577464  0.0  0.0   9544  6372 pts/10   S+   15:19   0:00 rg -L --hidden --no-ignore-vcs --glob !.git/* -i clojure-lsp
```

If I then delete the clj buffer completely, the `/bin/clojure-lsp` process is kept around by neovim/coc. Thus, if then I open up a new buffer of a clj file, there is nothing to load, the spinner doesn't display and clojure-lsp is immediately available.

I think that would suit you still, as having vim open and bouncing between files doesn't mean that clojure-lsp is unloaded and loaded each time. It's loaded once (on opening a clojure file) and kept around until vim quits.

If you can verify that your side, then I suppose reverting back to the original activationEvent would be appropriate.

**Comment by dharrigan** [comment]
Hi @NoahTheDuke, any chance of removing the activation events (so I can delete my fork? :-))

Thank you.

**Comment by NoahTheDuke** [comment]
Done, sorry for the delay.
